CREATE TABLE learn_item (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    front VARCHAR(200) NOT NULL,
    tip VARCHAR(1000),
    back VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) AUTO_INCREMENT=10000;

CREATE TABLE user_learn_item (
    item_id INT PRIMARY KEY NOT NULL,
    ef DOUBLE NOT NULL,
    n INT NOT NULL DEFAULT 0,
    is_Learning INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_learn_item FOREIGN KEY (item_id) REFERENCES learn_item(id)
);